export const PROVIDER_TIMEOUT_MS = {
  DEFAULT: 10_000,
  SCRAPE: 15_000,
} as const;

export const PROVIDER_LIMITS = {
  AMAZON_MAX_RESULTS: 3,
  GOODREADS_MAX_RESULTS: 3,
  COMICVINE_MAX_RESULTS: 10,
  DEFAULT_SEARCH_RESULTS: 10,
} as const;

export const PROVIDER_DELAYS_MS = {
  AMAZON_BETWEEN_REQUESTS: 800,
  GOODREADS_BETWEEN_REQUESTS: 600,
  HARDCOVER_RATE_LIMIT: 1_000,
  COMICVINE_VELOCITY_GUARD: 1_000,
} as const;
